-- ═══════════════════════════════════════════════════════════════════════════
-- GERADOR DO SCHEMA BASE — Sistema de Frota
--
-- O QUE É: o banco se auto-descreve. Rodar esta query no projeto de PRODUÇÃO
-- (SQL Editor ou MCP) devolve UMA LINHA POR COMANDO DDL, já na ordem certa:
--   extensões → sequences → tabelas → PK/UNIQUE/CHECK → FKs → índices
--   → funções → views → triggers → RLS off + GRANTs (política do projeto)
--
-- COMO USAR (IA via MCP ou humano):
--   1. Executar a query inteira no banco de produção.
--   2. Concatenar a coluna `stmt` (na ordem retornada) com quebra de linha dupla.
--   3. Salvar como db/schema_base_completo.sql
--   4. Conferir: deve ter ~53 CREATE TABLE (uma por tabela do public).
--
-- Esse arquivo gerado é o "passo 0" da implantação em cliente novo
-- (framework/03-deploy/implantacao-cliente.md, Bloco 1, item 0).
-- ═══════════════════════════════════════════════════════════════════════════

WITH secoes AS (

  -- 0) Cabeçalho
  SELECT 0 AS ord, 0::bigint AS sub,
    '-- SCHEMA BASE COMPLETO — Sistema de Frota (gerado do banco de produção em ' || now()::date || ')' || chr(10) ||
    '-- Rodar num projeto Supabase NOVO antes de qualquer migration de db/.' AS stmt

  -- 1) Extensões instaladas (menos plpgsql, que é nativa)
  UNION ALL
  SELECT 1, row_number() OVER (ORDER BY extname),
    'CREATE EXTENSION IF NOT EXISTS "' || extname || '";'
  FROM pg_extension WHERE extname <> 'plpgsql'

  -- 2) Sequences soltas (as de serial/identity nascem junto com a tabela)
  UNION ALL
  SELECT 2, row_number() OVER (ORDER BY sequence_name),
    'CREATE SEQUENCE IF NOT EXISTS public.' || quote_ident(sequence_name) || ';'
  FROM information_schema.sequences WHERE sequence_schema = 'public'

  -- 3) Tabelas (colunas com tipo exato, NOT NULL, DEFAULT e IDENTITY)
  UNION ALL
  SELECT 3, row_number() OVER (ORDER BY t.oid),
    'CREATE TABLE IF NOT EXISTS public.' || quote_ident(t.relname) || ' (' || chr(10) ||
    string_agg(
      '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
      || CASE WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
              WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
              ELSE '' END
      || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END
      || COALESCE(' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid), ''),
      ',' || chr(10) ORDER BY a.attnum
    ) || chr(10) || ');'
  FROM pg_class t
  JOIN pg_namespace n ON n.oid = t.relnamespace AND n.nspname = 'public'
  JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum > 0 AND NOT a.attisdropped
  LEFT JOIN pg_attrdef d ON d.adrelid = t.oid AND d.adnum = a.attnum
  WHERE t.relkind = 'r'
  GROUP BY t.oid, t.relname

  -- 4) PK / UNIQUE / CHECK (antes das FKs)
  UNION ALL
  SELECT 4, row_number() OVER (ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 ELSE 2 END, con.oid),
    'ALTER TABLE ONLY public.' || quote_ident(rel.relname) ||
    ' ADD CONSTRAINT ' || quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';'
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = rel.relnamespace AND n.nspname = 'public'
  WHERE con.contype IN ('p', 'u', 'c')

  -- 5) FOREIGN KEYs (depois que todas as tabelas existem)
  UNION ALL
  SELECT 5, row_number() OVER (ORDER BY con.oid),
    'ALTER TABLE ONLY public.' || quote_ident(rel.relname) ||
    ' ADD CONSTRAINT ' || quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';'
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = rel.relnamespace AND n.nspname = 'public'
  WHERE con.contype = 'f'

  -- 6) Índices que NÃO pertencem a constraints (esses já vieram acima)
  UNION ALL
  SELECT 6, row_number() OVER (ORDER BY indexname),
    indexdef || ';'
  FROM pg_indexes
  WHERE schemaname = 'public'
    AND indexname NOT IN (SELECT conname FROM pg_constraint)

  -- 7) Funções do projeto (exclui as que pertencem a extensões)
  UNION ALL
  SELECT 7, row_number() OVER (ORDER BY p.oid),
    pg_get_functiondef(p.oid) || ';'
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace AND n.nspname = 'public'
  WHERE p.prokind = 'f'
    AND NOT EXISTS (SELECT 1 FROM pg_depend dep WHERE dep.objid = p.oid AND dep.deptype = 'e')

  -- 8) Views (ordem de criação = ordem de dependência na prática)
  UNION ALL
  SELECT 8, row_number() OVER (ORDER BY c.oid),
    'CREATE OR REPLACE VIEW public.' || quote_ident(c.relname) || ' AS' || chr(10) ||
    pg_get_viewdef(c.oid, true)
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
  WHERE c.relkind = 'v'

  -- 9) Triggers (as funções já existem na seção 7)
  UNION ALL
  SELECT 9, row_number() OVER (ORDER BY t.oid),
    pg_get_triggerdef(t.oid) || ';'
  FROM pg_trigger t
  JOIN pg_class rel ON rel.oid = t.tgrelid
  JOIN pg_namespace n ON n.oid = rel.relnamespace AND n.nspname = 'public'
  WHERE NOT t.tgisinternal

  -- 10) Política do projeto: RLS OFF + GRANT ALL (estado real do banco hoje;
  --     multi-tenant com RLS é fase futura — decisão registrada do dono)
  UNION ALL
  SELECT 10, row_number() OVER (ORDER BY c.relname),
    'ALTER TABLE public.' || quote_ident(c.relname) || ' DISABLE ROW LEVEL SECURITY;'
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
  WHERE c.relkind = 'r'

  UNION ALL
  SELECT 11, 1,
    'GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;' || chr(10) ||
    'GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;' || chr(10) ||
    'GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;' || chr(10) ||
    'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;' || chr(10) ||
    'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;'
)
SELECT stmt FROM secoes ORDER BY ord, sub;
